export const SITE_ACTION_STATUSES = ['pending', 'in_progress', 'failed', 'done', 'requires_action'] as const;
export type SiteActionStatusValue = typeof SITE_ACTION_STATUSES[number];

export const SITE_ACTION_ORIGINS = ['dashboard', 'agent', 'schedule', 'system'] as const;

/** @see https://api.docs.modulards.com/modular-ds-public-api/site-actions/list-site-actions */
export const SITE_ACTION_TYPES = [
  'manager.install',
  'manager.activate',
  'manager.deactivate',
  'manager.delete',
  'manager.upgrade',
  'manager.safe_upgrade',
  'manager.update',
  'screenshot',
  'security.patchstack.create',
  'security.patchstack.remove',
  'malware_scan.site_creation',
  'malware_scan.site_removal',
  'malware_scan.site_plan_update',
  'malware_scan.run',
  'manager.user.create',
  'manager.user.update',
  'manager.user.delete',
  'manager.user.index',
  'backup.restoration',
  'backup.migration_new_domain',
  'backup.migration_same_domain',
  'backup.migration_existing_site',
  'backup.create_staging',
  'health.refresh',
  'after_validate_connection',
  'broken_link.scan',
  'redirection.sync',
] as const;

export const SITE_ACTION_ITEM_TYPES = [
  'site.manager.safe-upgrade.backup',
  'site.manager.safe-upgrade.capture_before',
  'site.manager.safe-upgrade.ping_check',
  'site.manager.safe-upgrade.capture_after',
  'site.manager.safe-upgrade.compare_visual',
  'site.manager.safe-upgrade.validation',
  'site.manager.safe-upgrade.rollback',
  'site.manager.safe-upgrade.cleanup',
  'site.manager.activate',
  'site.manager.deactivate',
  'site.manager.delete',
  'site.manager.upgrade',
  'screenshot',
  'site.manager.install',
  'site.manager.user.create',
  'site.manager.user.update',
  'site.manager.user.delete',
  'site.manager.user.index',
  'security.patchstack.site_creation',
  'security.patchstack.plugin_download',
  'security.patchstack.plugin_validation',
  'security.patchstack.site_validation',
  'security.patchstack.configure',
  'security.patchstack.rollback',
  'malware_scan.site_creation',
  'malware_scan.site_removal',
  'malware_scan.site_plan_update',
  'malware_scan.verify_connection',
  'malware_scan.manifest_core',
  'malware_scan.manifest_plugins',
  'malware_scan.manifest_themes',
  'malware_scan.manifest_mu_plugins',
  'malware_scan.manifest_content',
  'malware_scan.manifest_uploads',
  'malware_scan.manifest_database',
  'malware_scan.merge_manifest',
  'malware_scan.scan_files',
  'malware_scan.scan_database',
  'broken_link.verify_connection',
  'broken_link.plugin_initiate',
  'broken_link.manifest_part',
  'broken_link.scan_part',
  'redirection.verify_connection',
  'redirection.upload_payload',
  'redirection.plugin_push',
  'backup.verify_credentials',
  'backup.restore',
  'backup.migrate',
  'backup.permission_check',
  'backup.verify_connection',
  'backup.rollback',
  'backup.restoration_cleanup',
  'migration.wp_config_update',
  'migration.search_replace',
  'migration.oauth_update',
  'migration.prefix_change',
  'migration.search_engine_visibility',
  'migration.plugin.preparation',
  'migration.create_target_site',
  'site.manager.server.information',
  'site.manager.update',
  'health.async_authorization_header',
  'health.async_background_updates',
  'health.async_dotorg_communication',
  'health.async_https_status',
  'health.async_loopback_requests',
  'health.async_rest_availability',
  'health.server_checks',
  'health.items_checks',
  'health.vulnerability_generate',
  'health.vulnerability_check',
  'health.site_score',
  'health.patchstack_check',
] as const;
